package com.example.camerademo;

public class ConstantsUtil {

	public static final String CHECK_INTERNET_EN = "Internet connection not available.";
	public static final String LOADING_TXT = "Loading...";
	public static final String VERYFING_TXT = "Verifying ...";
	public static final String VERYFING_PIN_TXT = "Verifying Pin...";
	public static final String PASSWORD_INVALID = "Please Enter Valid Password.";
	public static final String CONTACT_ADMIN_FOR_PASSWORD = "Please call Administrator ";
	public static final String USE_FORGOT_PASSWORD = "OR use \"Forgot Password\" feature";
	public static final String INCORRECT_PASSWORD = "Incorrect Password.";
	public static final String KEY_CORRUPTED = "Key Corrupted.";
	public static final String ERROR_MSG_RECEIVED = "Error occurred. Please retry!";
	public static final String CHANGE_ADMIN_FIRST_ALERT = "Please assign admin privilege to a member before exiting group";
	public static final String CHANGE_ADMIN_SELF_ALERT = "You are the group admin already";
	public static final String NO_MESSAGE_KEY_ALERT = "Please wait until group is initialized.";
	public static final String APP_CALL_PRIORITY_SET_ALERT = "Call priority set for Mraijeb call. GSM call received during Mraijeb call will be rejected.";
	public static final String GSM_CALL_PRIORITY_SET_ALERT = "Call priority set for GSM call. Mraijeb call will be either put on hold or rejected..";
	public static final String VOLUME_UP_MESSAGE = "Please turn the volume up.";

	public static final String RegistrationActivity_select_your_country = "Select your country";
	public static final String RegistrationActivity_you_must_specify_your_country_code = "You must specify your country code.";
	public static final String RegistrationActivity_you_must_specify_your_phone_number = "You must specify your phone number.";
	public static final String RegistrationActivity_you_must_specify_your_pin = "You must specify your 6 digit Pin Received.";
	public static final String RegistrationActivity_you_must_specify_your_password = "Password and confirm password should not be empty.";
	public static final String RegistrationActivity_password_mismatch = "Password Mismatch.";
	public static final String RegistrationActivity_password_incorrect = "Incorrect Password.";
	public static final String APP_CORREPTED = "Application corrupted. Please reinstall application.";
	public static final String UPDATE_CONTACT_STARTED_MSG = "Updating Contacts Started";
	public static final String profile_details_updated = "Profile Details Successfully Updated";
	public static final String GroupActivity_you_must_specify_your_group_name = "You must specify your Group Name.";
	public static final String GroupActivity_group_name_limit = "Group name should not be morethan 32 characters";
	public static final String GroupActivity_you_must_have_min_Member = "You must select atleast one member.";
	public static final String GroupActivity_group_created = "Group Successfully Created";
	public static final String GroupActivity_group_create_fail = "Group Creation Failed. Please Try Again";
	public static final String NOT_REGISTERED = "Network error. Please check internet connection! \n You must be registered to utilize this feature.";
	public static final String BCard_you_must_specify_your_Contact_name = "You must specify Contact Name.";
	public static final String BCard_you_must_have_min_one_selected = "You must select atleast one field to send.";
	public static final String STATUS_UPDATED_MSG = "Status Updated";
	public static final String UNABLE_TO_PROCESS_REQ_EN = "Unable to process your request. Please try again later.";
	public static final String ACTIVATE_SCREEN_MSG = "Screen Awake Activated";
	public static final String DEACTIVATE_SCREEN_MSG = "Screen Awake Deactivated";
	public static final String PHONE_ROOTED_MSG = "Your Phone is rooted. " + "\n"
			+ "Mraijeb can not run on rooted phones.";
	public static final String CHECK_AUTHENTICATION_EN = "Authentication Failed Due To Server Error, Please Try Again Later.";
	public static final String CHANGE_NUMBER_ALERT_EN = "This will clear all your Messages, Group history and application will restart or exit.\nPlease Signup with a new number.\nAre you sure want to continue?";

	public static final String GET_DEVICE_NAME = "DEVICE_NAME";
	public static final String GET_IMEI_NUMBER = "IMEI_NUMBER";
	public static final String GET_DEVICE_LOCAL_IP = "DEVICE_LOCAL_IP";
	public static final String GET_SERVER_PUBLIC_IP = "GET_SERVER_PUBLIC_IP";
	public static final String GET_SERVER_PUBLIC_PORT = "GET_SERVER_PUBLIC_PORT";
	public static final String GET_ST_PORT = "GET_ST_PORT";
	public static final String GET_REMOTE_FORWARD_PORT = "GET_REMOTE_FORWARD_PORT";
	public static final String GET_COMMAND_CONNECTION_TYPE = "GET_COMMAND_CONNECTION_TYPE";
	public static final String GET_VOICE_CONNECTION_TYPE = "GET_VOICE_CONNECTION_TYPE";
	public static final String GET_VIDEO_CONNECTION_TYPE = "GET_VIDEO_CONNECTION_TYPE";
	public static final String GET_ST_LOCAL_PORT = "GET_ST_LOCAL_PORT";
	public static final String GET_APP_KEY = "GET_APP_KEY";
	public static final String GET_XM_STRING = "GET_XM_STRING";
	public static final String GET_BIOMETRIC_XM_STRING = "GET_BIOMETRIC_XM_STRING";
	public static final String GET_BIOMETRIC_XM_IV_STRING = "GET_BIOMETRIC_XM_IV_STRING";
	public static final String GET_XM_CALL_STRING = "GET_XM_CALL_STRING";
	public static final String GET_ENC_SALT_PASSWORD = "GET_ENC_SALT_PASSWORD";
	public static final String GET_ITERATION_SALT = "GET_ITERATION_SALT";
	public static final String GET_FORCEFUL_REGISTRAR_DONE = "GET_FORCEFUL_REGISTRAR_DONE";
	public static final String GET_MOB_NUM = "GET_MOB_NUM";
	public static final String GET_CALL_ALIAS_RAND_NUM = "GET_CALL_ALIAS_RAND_NUM";
	public static final String GET_CONT_CODE = "GET_CONT_CODE";
	public static final String GET_CLIENT_ECC_DH_PRIVATE_KEY = "GET_CLIENT_ECC_DH_PRIVATE_KEY";
	public static final String GET_CLIENT_ECC_DH_PUBLIC_KEY = "GET_CLIENT_ECC_DH_PUBLIC_KEY";
	public static final String GET_CLIENT_ECC_DSA_PRIVATE_KEY = "GET_CLIENT_ECC_DSA_PRIVATE_KEY";
	public static final String GET_CLIENT_ECC_DSA_PUBLIC_KEY = "GET_CLIENT_ECC_DSA_PUBLIC_KEY";
	public static final String GET_SERVER_ECC_PUBLIC_X_KEY = "GET_SERVER_ECC_PUBLIC_X_KEY";
	public static final String GET_SERVER_ECC_PUBLIC_Y_KEY = "GET_SERVER_ECC_PUBLIC_Y_KEY";
	public static final String GET_BULK_MESSAGE_ACK = "GET_BULK_MESSAGE_ACK";
	public static final String GET_CLIENT_CALL_ECC_DH_PRIVATE_KEY = "GET_CLIENT_CALL_ECC_DH_PRIVATE_KEY";
	public static final String GET_CLIENT_CALL_ECC_DH_PUBLIC_KEY = "GET_CLIENT_CALL_ECC_DH_PUBLIC_KEY";
	public static final String GET_CLIENT_CALL_ECC_DSA_PRIVATE_KEY = "GET_CLIENT_CALL_ECC_DSA_PRIVATE_KEY";
	public static final String GET_CLIENT_CALL_ECC_DSA_PUBLIC_KEY = "GET_CLIENT_CALL_ECC_DSA_PUBLIC_KEY";
	public static final String GET_CLIENT_CALL_ECC_DH_PRIVATE_IV = "GET_CLIENT_CALL_ECC_DH_PRIVATE_IV";
	public static final String GET_CLIENT_CALL_ECC_DH_PUBLIC_IV = "GET_CLIENT_CALL_ECC_DH_PUBLIC_IV";
	public static final String GET_CLIENT_CALL_ECC_DSA_PRIVATE_IV = "GET_CLIENT_CALL_ECC_DSA_PRIVATE_IV";
	public static final String GET_CLIENT_CALL_ECC_DSA_PUBLIC_IV = "GET_CLIENT_CALL_ECC_DSA_PUBLIC_IV";
	public static final String GET_CLIENT_CALL_MAP_KEY = "GET_CLIENT_CALL_MAP_KEY";
	public static final String GET_CLIENT_CALL_MAP_IV = "GET_CLIENT_CALL_MAP_IV";
	public static final String GET_SERVER_PUBLIC_IP_KEY = "GET_SERVER_PUBLIC_IP_KEY";// CALLFROMNOT
	public static final String GET_SERVER_PUBLIC_PORT_KEY = "GET_SERVER_PUBLIC_PORT_KEY";// CALLFROMNOT
	public static final String GET_CLIENT_MOBILE_NUMBER_KEY = "GET_CLIENT_MOBILE_NUMBER_KEY";// CALLFROMNOT
	public static final String GET_SERVER_PUBLIC_IP_IV = "GET_SERVER_PUBLIC_IP_IV";// CALLFROMNOT
	public static final String GET_SERVER_PUBLIC_PORT_IV = "GET_SERVER_PUBLIC_PORT_IV";// CALLFROMNOT
	public static final String GET_CLIENT_MOBILE_NUMBER_IV = "GET_CLIENT_MOBILE_NUMBER_IV";// CALLFROMNOT
	public static final String GET_OFFLINE_CALL_LOG = "GET_OFFLINE_CALL_LOG";// CALLFROMNOT
	public static final String FORGET_PASSWORD_ADMIN_MOBILE_NUMBER = "FORGET_PASSWORD_ADMIN_MOBILE_NUMBER";
	public static final String SECURITY_ADMIN_MOBILE_NUMBER = "SECURITY_ADMIN_MOBILE_NUMBER";
	public static final String BACKGROUND_GONE_TIME = "BACKGROUND_GONE_TIME";
	public static final String GET_OLD_MOB_NUM = "GET_OLD_MOB_NUM";
	public static final String GET_LATEST_SERVER_ID = "GET_LATEST_SERVER_ID";
	public static final String GET_NAME = "NAME";
	public static final String GET_NAME_FULL = "NAME_FULL";
	public static final String GET_PIN_NUM = "GET_PIN_NUM";
	public static final String GET_ATT_COUNT = "GET_ATT_COUNT";
	public static final String GET_ATT_URL = "GET_ATT_URL";
	public static final String GET_PROF_PIC_URL = "GET_PROF_PIC_URL";
	public static final String GET_IM_NOW = "GET_IM_NOW";
	public static final String GET_CONTACT_OBJ = "GET_CONTACT_OBJ";
	public static final String GET_MSG_SHOW_LIMIT = "GET_MSG_SHOW_LIMIT";
	public static final String GET_MSG_DELETE_COUNT = "GET_MSG_DELETE_COUNT";
	public static final String GET_BRIEFCASE_DELETE_COUNT = "GET_BRIEFCASE_DELETE_COUNT";
	public static final String GET_MSG_DELETE_COUNT_PERIOD = "GET_MSG_DELETE_COUNT_PERIOD";
	public static final String GET_PASSWORD_SHOW_COUNT = "GET_PASSWORD_SHOW_COUNT";
	public static final String GET_BRIEFCASE_PASSWORD = "GET_BRIEFCASE_PASSWORD";
	public static final String GET_PASSWORD_SHOW_COUNT_PERIOD = "GET_PASSWORD_SHOW_COUNT_PERIOD";
	public static final String GET_AUTO_DOWNLOAD_OPTION = "GET_AUTO_DOWNLOAD_OPTION";
	public static final String GET_WRONG_PASSWORD_COUNT = "GET_WRONG_PASSWORD_COUNT";
	public static final String GET_CRASH_COUNT = "GET_CRASH_COUNT";
	public static final String GET_CRASH_DATE_TIME = "GET_CRASH_DATE_TIME";
	public static final String GET_PASSWORD_VERIFY_STATUS = "GET_PASSWORD_VERIFY_STATUS";
	public static final String GET_CHAT_FONT_SIZE = "GET_CHAT_FONT_SIZE";
	public static final String GET_ACTIVE_SERVER_DOMAIN = "GET_ACTIVE_SERVER_DOMAIN";
	public static final String GET_FAVORITE_CONTACTS = "GET_FAVORITE_CONTACTS";
	public static final String GET_MRAJIB_CALL_PRIORITIZE = "GET_MRAJIB_CALL_PRIORITIZE";
	public static final String GET_BIOMETRIC_AUTHENTICATION_STATUS = "GET_BIOMETRIC_AUTHENTICATION_STATUS";
	public static final String BCARD_ACTION_TITLE = "Business Card";
	public static final String THUMPEXT = "thump";
	public static final String ORG_EXT = "org.mp4";
	public static final String ORG_IMAGE_EXT = "org.jpg";
	public static final String ORG_VIDEO_EXT = "org.mp4";
	public static final String TODAY_TXT = "Today";
	public static final String yesterday = "Yesterday";
	public static final String BC_ANDROID = "BCAndroid";
	public static final String BROADCAST_NAME = "<<Broadcast>>";
	public static final String Version4 = "V_4";
	public static final String Version5 = "V_5";

	public static final String SOCKET_CONNECT = "SocketConnect";
	public static final String REGISTRATION = "Registration";
	public static final String SIGNUP1 = "SignUp1";
	public static final String SIGNUPPIN = "SignUp2";
	public static final String SIGNUPPASSWORD = "SignUp3";
	public static final String IS_SOCKET_CONNECTED = "IsSocketConnected";
	public static final String IS_ACTIVITY_CHANGED = "IS_ACTIVITY_CHANGED";

	public static final String ITERATION_SALT = "cb12ca91c7b790fba9f0304d";
	public static final String ITERATION_ALGORITHM = "PBKDF2WithHmacSHA1";
	public static final int DERIVED_KEY_LENGTH_PASSWORD = 256;
	public static final int ECIS_AES_KEY_LEN = 32;
	public static final int MESSAGE_CHUNK_MAX_LEN = 512;
	public static final int DERIVED_KEY_LENGTH_ECIS = (64 * 8);
	public static final int ITERATION_COUNT_PASSWORD = 10000;
	public static final int ITERATION_COUNT_ECIS = 1;
	public static final int PIN_COUNT = 6;
	public static final int MIN_PASS_COUNT = 6;
	public static final int MAX_PASS_COUNT = 32;
	public static final int MIN_RAND_COUNT = 100;
	public static final int MAX_RAND_COUNT = 999;
	public static final String RegistrationActivity_password_limit_en = "The password must be "
			+ ConstantsUtil.MIN_PASS_COUNT + " - " + ConstantsUtil.MAX_PASS_COUNT + " characters.";
	public static final String RegistrationActivity_password_enforce_en = "Atleast one alphabet and one number.";
	public static final int MAX_WRONG_PASSWORD_ATTEMPT = 5;

	public static final int MAX_GROUP_MEMBER_AT_A_TIME = 30;
	public static final String MAX_GROUP_MEMBER_AT_A_TIME_TXT = "Maximum group member added at a time is 30. limit reached.";

	public static final int MAX_MESSAGES_AT_A_TIME = 25;

	public static final int MAX_ACK_SEND = 20;
	public static final int MAX_PROFILE_GET_SEND = 30;
	public static final int REG_NORMAL_MODE = 0;
	public static final int REG_AFTER_SIGNUP_MODE = 1;

	// Message Content Type
	// -------------------------
	public static final String TEXT = "1";
	public static final String IMAGE = "2";
	public static final String AUDIO = "3";
	public static final String VIDEO = "4";
	public static final String BCARD = "5";
	public static final String LOCATION = "6";
	public static final String FILE = "8";
	public static final String THUMPNAIL = "7";
	public static final String USERPROFILEPIC = "9";
	public static final String GROUPPROFILEPIC = "10";
	public static final String USERPROFILESTATUS = "11";
	public static final String PTT = "12";
	public static final String BRIEFCASE = "13";
	public static final String TEMP = "14";
	public static final String SAVELOCAL = "15";
	public static final String CRT = "16";

	public static final String INCOMING = "IN";
	public static final String OUTGOING = "OUT";
	public static final String SERVER = "SERVER";
	public static final String MSGTYPE_USER = "1";
	public static final String MSGTYPE_GROUP = "2";
	public static final String MSGTYPE_CONFIRMATION = "3";
	public static final String MSGTYPE_SERVER = "4";
	public static final String MSGTYPE_BROADCAST = "5";
	public static final String KEYTYPE_KEY = "KEYTYPE";
	public static final String CERTIFICATEID_KEY = "CERTIFICATEID_KEY";
	public static final String REQUESTKEYID_KEY = "REQUESTKEYID_KEY";
	public static final String CERTIFICATEACTIVEMODE_KEY = "CERTIFICATEACTIVEMODE_KEY";
	public static final String CERTIFICATESTATUS_KEY = "CERTIFICATESATUS_KEY";
	public static final String MOBILENUMBERS_KEY = "MOBILENUMBERS";
	public static final String KEYTYPE_PUBLIC = "1";
	public static final String KEYTYPE_MESSAGE = "2";
	public static final String KEYTYPE_SIGNED_CERTIFICATE = "3";
	public static final String KEYTYPE_SIGNED_MESSAGING_SERVER_CERTIFICATE = "4";
	public static final String KEYTYPE_FORWARD= "1";
	public static final String KEYTYPE_RESEND = "2";
	public static final String SUCESS = "2";
	public static final String DSAFAILED = "7";
	public static final String ENCRYPTIONFAILED = "8";
	public static final String CERTIFICATENOTFOUND = "9";
	public static final String CERTIFICATEDSAVERIFYFAILED = "10";
	public static final String SUCESSSENDIMREG = "11";
	public static final String IMREG_ID = "SERVERID";
	public static final String IMREG_ChatType = "MESSAGETYPE";
	public static final String IMREG_GroupId = "GROUPID";
	public static final String IMREG_MobileNumber = "MOBILENUMBER";
	public static final String IMREG_ResendRequestId = "REQUESTID";
	public static final String IMREG_ResendStatus = "REQUESTSTATUS";
	public static final String IMREG_KeyLength = "KEYCOMPOLENGTH";
	public static final String IMREG_KeyForMode = "KEYFORMODE";
	public static final String IMREG_ChunkId = "CHUNKID";
	public static final String IMREG_GChunkLast = "CHUNKL";
	public static final String IMREG_MessageForward = "MESSAGEFORWARD";
	public static final String IMREG_KeyNumberKeyCompo = "KEYNUMBERCOMPO";
	public static final String IMREG_KeyGenerationMode = "KEYGENERATIONMODE";
	public static final String IMREG_ServerReqField = "SERVERKEYFIELD";
	public static final String IMREG_DeliveryStatus = "DELIVERYSTATUS";
	public static final String IMREG_CertificateId = "CERTIFICATEID";
	public static final String TABLE_CONTACT_CHAT_HISTORY = "ContactChatHistory";
	public static final String TABLE_CHAT_RECENT = "ChatRecent";
	public static final String TABLE_CONTACTS = "Contacts";
	public static final String TABLE_GROUPS = "Groups";
	public static final String TABLE_CALL_LOG_RECENT = "CallLogRecent";
	public static final String TABLE_CALL_LOG_HISTORY = "CallLogHistory";
	public static final String TABLE_PROFILE_STATUS = "ProfileStatus";
	public static final String TABLE_GENERAL_PREFERENCES = "Preferences";
	public static final String TABLE_BRIEFCASE_CHAT_TABLE = "BriefcaseChat";
	public static final String TABLE_CONTACTS_SESSION = "ChatSession";
	public static final String TABLE_CHAT_INFO = "ChatDetailsInfo";
	public static final String GENERAL_ID = "_id";
	public static final String GENERAL_KEY = "pkey";
	public static final String GENERAL_VALUE = "pvalue";
	public static final String CHAT_SESSION_ID = "_id";
	public static final String CHAT_SESSION_MOBILE_NUMBER = "recipientNumber";
	public static final String CHAT_SESSION_DH_PUBLIC_KEY_X = "recipientDHPublicKeyX";
	public static final String CHAT_SESSION_DH_PUBLIC_KEY_Y = "recipientDHPublicKeyY";
	public static final String CHAT_SESSION_CERTIFICATE_ID = "recipientCertificateId";
	public static final String CHAT_SESSION_DSA_PUBLIC_KEY_X = "recipientDSAPublicKeyX";
	public static final String CHAT_SESSION_DSA_PUBLIC_KEY_Y = "recipientDSAPublicKeyY";
	public static final String CALL_SESSION_DH_PUBLIC_KEY_X = "recipientCallDHPublicKeyX";
	public static final String CALL_SESSION_DH_PUBLIC_KEY_Y = "recipientCallDHPublicKeyY";
	public static final String CALL_SESSION_DSA_PUBLIC_KEY_X = "recipientCallDSAPublicKeyX";
	public static final String CALL_SESSION_DSA_PUBLIC_KEY_Y = "recipientCallDSAPublicKeyY";
	public static final String IM_CHAT_ID = "_id";
	public static final String IM_READ_STATUS = "readStatus";
	public static final String IM_SENDER_TYPE = "type";
	public static final String IM_DELIVERED_TIME = "time";
	public static final String IM_CHAT_DIRECTION = "direction";
	public static final String IM_MOBILE = "mobile";
	public static final String IM_GROUP_ID = "groupID";
	public static final String IM_MESSAGE_ID = "chatID";
	public static final String IM_ATT_LOAD_STATUS = "loadStatus";
	public static final String IM_ATT_ENCRYPT = "encryptMedia";
	public static final String IM_ATT_SIZE = "attachmentSize";
	public static final String IM_READ_TIME = "readTime";
	public static final String IM_IS_ZIP = "isZip";
	public static final String IM_ATT_PATH = "attachmentPath";
	public static final String IM_CONTENT_TYPE = "contentType";
	public static final String IM_FILE_NAME = "fileName";
	public static final String IM_FILE_ATT_PAGE_COUNT = "attPageCount";
	public static final String BRIEFCASE_CLIENT_ID = "clientId";
	public static final String BRIEFCASE_SERVER_ID = "serverId";
	public static final String IM_MEDIA_ID = "mediaId";
	public static final String IM_CONTACT_NAME = "name";
	public static final String IM_ENTITY_TYPE = "entityType";
	public static final String IM_UNREAD = "unRead";
	public static final String IM_PARENT_MESSAGE_ID = "parentId"; // Added by OS-0028
	public static final String IM_MESSAGE_KEY = "messageKey";
	public static final String IM_SHUFFLE_KEY = "shuffleKey";
	public static final String IM_ACTION_TYPE = "actionType";
	public static final String IM_FROM_RECIVED = "IMFromRecived";
	public static final String CALL_LOG_ID = "_id";
	public static final String CALL_LOG_MOBILE = "mobile";
	public static final String CALL_LOG_GROUP_ID = "groupID";
	public static final String CALL_LOG_CALL_TYPE = "callType";
	public static final String CALL_LOG_CALL_COUNT = "callCount";
	public static final String CALL_LOG_CALL_SERVICE_TYPE = "callServiceType";
	public static final String CALL_LOG_TEXT = "text";
	public static final String CALL_LOG_TIME = "time";
	public static final String CALL_LOG_CALL_VALID = "isValid";
	public static final String CALL_LOG_HISTORY_ID = "_id";
	public static final String CALL_LOG_HISTORY_MOBILE = "mobile";
	public static final String CALL_LOG_HISTORY_GROUP_ID = "groupID";
	public static final String CALL_LOG_HISTORY_CALL_TYPE = "callType";
	public static final String CALL_LOG_HISTORY_CALL_SERVICE_TYPE = "callServiceType";
	public static final String CALL_LOG_HISTORY_START_TIME = "time";
	public static final String CALL_LOG_HISTORY_CALL_STATUS_TEXT = "statusText";
	public static final String CALL_LOG_HISTORY_TEXT = "text";
	public static final String CALL_LOG_HISTORY_CALL_DURATION = "duration";
	public static final String CALL_LOG_HISTORY_CALL_VALID = "isValid";
	public static final String GROUP_CREATE_ID = "_id";
	public static final String GROUP_CREATE_GROUP_NAME = "groupName";
	public static final String GROUP_CREATE_DATE = "creationDate";
	public static final String GROUP_CREATE_GROUP_ACTIVE = "active";
	public static final String GROUP_CREATE_GROUP_ID = "groupID";
	public static final String GROUP_CREATE_GROUP_MEMBER = "groupMember";
	public static final String GROUP_CREATE_GROUP_OWNER = "owner";
	public static final String GROUP_CREATE_GROUP_KEY = "groupKey";
	public static final String GROUP_CREATE_GROUP_KEY_ID = "groupKeyId";
	public static final String GROUP_CREATE_GROUP_SHUFFLE_KEY = "groupShuffleKey";
	public static final String GROUP_UNKNOWN_GROUP_NAME = "Unknown Group";
	public static final String CHAT_INFO_ID = "_id";
	public static final String CHAT_INFO_GROUP_ID = "groupId";
	public static final String CHAT_INFO_CHAT_ACTION_STATUS = "messageActionStatus";
	public static final String CHAT_INFO_SERVER_CHAT_ID = "serverMessageId";
	public static final String CHAT_INFO_DELIVERED_INFO = "receiverDeliveredTime";
	public static final String CHAT_INFO_READ_INFO = "receiverReadTime";
	public static final String NICKNAME_CMD = "1";
	public static final String PASSWORD_NEW_CMD = "2";
	public static final String ADMIN_RESET_PASSWORD_CMD = "3";
	public static final String GROUP_CREATE_CMD = "1";
	public static final String GROUP_INVITE_CMD = "2";
	public static final String GROUP_INVITE_ACK_CMD = "3";
	public static final String GROUP_JOIN_CMD = "4";
	public static final String GROUP_DISJOIN_CMD = "5";
	public static final String GROUP_BLOCK_CMD = "6";
	public static final String GROUP_ADD_CMD = "7";
	public static final String GROUP_EDIT_CMD = "8";
	public static final String GROUP_UPDATE_ACK_CMD = "9";
	public static final String GROUP_ADMIN_CMD = "10";
	public static final String GROUP_MEMBER_REMOVE = "0";
	public static final String GROUP_MEMBER_ADD = "1";
	public static final String GROUP_ADMIN_CHANGE = "3";
	public static final int GROUP_ACTIVE = 1;
	public static final int GROUP_NOT_ACTIVE = 0;
	public static final int IM_SEND_STATUS_PENDING = 1;
	public static final int IM_SEND_STATUS_DELIVERED = 2;
	public static final int IM_SEND_STATUS_FAILED = 3;
	public static final int IM_SEND_STATUS_READ = 4;
	public static final int IM_SEND_STATUS_NOT_SENT = 5;
	public static final int IM_SEND_STATUS_CLOSED = 6;
	public static final int IM_SEND_STATUS_IMREG_ERROR = 8;
	public static final int IM_SEND_STATUS_IM_ERROR = 9;
	public static final int IMREG_STATUS_SUCCESS = 12;
	public static final int IMREG_STATUS_NOMESSAGEKEY = 13;
	public static final int IM_SEND_STATUS_DELETED = 14;
	public static final String CALL_TAB = "Calls";
	public static final String CHAT_TAB = "Chats";
	public static final String CONTACT_TAB = "Contacts";
	public static final String GROUP_TAB = "Groups";
	public static final String MEDIA_TAB = "Media";
	public static final String FILES_TAB = "Documents";
	public static final String MANAGE_STORAGE_ACTION_TITLE = "Manage Storage";
	public static final String NEW_GROUP_ACTION_TITLE = "New Group";
	public static final String GROUP_ACTION_TITLE = "Groups";
	public static final String SETTINGS_ACTION_TITLE = "Settings";
	public static final String MORE_ACTION_TITLE = "More";
	public static final String DISTRIBUTE_ACTION_TITLE = "Distribute";
	public static final String PROFILE_SETTINGS_ACTION_TITLE = "Profile";
	public static final String CHAT_SETTINGS_ACTION_TITLE = "Chat Settings";
	public static final String SECURITY_SETTINGS_ACTION_TITLE = "Security Settings";
	public static final String TECH_SUPPORT_ACTION_TITLE = "Technical Support";
	public static final String WEB_SUPPORT_ACTION_TITLE = "Web Support";
	public static final String BROADCAST_ACTION_TITLE = "Broadcast";
	public static final String ADMIN_RESET_ACTION_TITLE = "Passwor Reset";
	public static final String FORGET_PASSWORD_ACTION_TITLE = "Forgot Password";
	public static final String Dialer_ACTION_TITLE = "Dialer";
	public static final String CHAT_FORWARD_TITLE = "Select chat";
	public static final String CALL_LOG_TITLE = "Call Log";
	public static final String MEDIA_TITLE = "Media";
	public static final String BRIEFCASE_TITLE = "Briefcase";
	public static final String DOC_ACTION_TITLE = "Choose Document";
	public static final String APP_DOWNLOAD_TITLE = "Update";
	public static final String PASSWORD_SETTINGS_ACTION_TITLE = "Change Password";
	// MessagingApp Attachment upload actions
	// -------------------------------------
	public static final int attach_photo = 0;
	public static final int attach_gallery = 9;
	public static final int attach_video = 1;
	public static final int attach_contact = 2;
	public static final int attach_location = 3;
	public static final int attach_file = 4;
	public static final int attach_audio = 5;
	public static final int attach_document = 6;
	public static final int attach_video_play = 7;
	public static final int attach_fileView = 8;
	public static final int attach_hide = 10;
	public static final int RESULT_CLOSE_ALL = 11;
	public static final int SCREEN_OVERLAYS = 12;

	public static final int MEDIA_DIR_IMAGE = 0;
	public static final int MEDIA_DIR_AUDIO = 1;
	public static final int MEDIA_DIR_VIDEO = 2;
	public static final int MEDIA_DIR_DOCUMENT = 3;
	public static final int MEDIA_DIR_CACHE = 4;
	public static final String FILE_DOC_PAGES = "Pages";
	public static final String FILE_PPT_SLIDES = "Slides";
	public static final String FILE_EXCEL_SHEETS = "Sheets";
	public static final String FILE_DOC_SINGLE_PAGES = "Page";
	public static final String FILE_PPT_SINGLE_SLIDES = "Slide";
	public static final String FILE_EXCEL_SINGLE_SHEETS = "Sheet";
	/* upload */
	public static final String ATT_NOT_UPLOADED = "0";
	public static final String ATT_UPLOADING = "1";
	public static final String ATT_UPLOADED = "2";
	public static final String ATT_UPLOAD_FAIL = "3";
	/* Download */
	public static final String ATT_NOT_DOWNLOADED = "4";
	public static final String ATT_DOWNLOADING = "5";
	public static final String ATT_DOWNLOADED = "6";
	public static final String ATT_DOWNLOAD_FAIL = "7";
	public static final String ATT_ABORTING = "8";

	public static final String ATT_CRYPTO_ERROR = "9";

	public static final String ATT_NOT_FORWARED = "0";
	public static final String ATT_FORWARED = "1";

	public static final int VIEW_PROG = 0;
	public static final int VIEW_ITEM = 1;
	public static final int VIEW_IM_UP = 2;
	public static final int VIEW_IM_UP_CONT = 3;
	public static final int VIEW_IM_DOWN = 4;
	public static final int VIEW_IM_DOWN_CONT = 5;
	public static final int VIEW_ATT_IMGVDO_UP = 6;
	public static final int VIEW_ATT_IMGVDO_UP_CONT = 7;
	public static final int VIEW_ATT_IMGVDO_DOWN = 8;
	public static final int VIEW_ATT_IMGVDO_DOWN_CONT = 9;
	public static final int VIEW_ATT_AUDIO_UP = 10;
	public static final int VIEW_ATT_AUDIO_UP_CONT = 11;
	public static final int VIEW_ATT_AUDIO_DOWN = 12;
	public static final int VIEW_ATT_AUDIO_DOWN_CONT = 13;
	public static final int VIEW_BCARD_UP = 14;
	public static final int VIEW_BCARD_UP_CONT = 15;
	public static final int VIEW_BCARD_DOWN = 16;
	public static final int VIEW_BCARD_DOWN_CONT = 17;
	public static final int VIEW_SERVER = 18;
	public static final int VIEW_ATT_FILE_UP = 19;
	public static final int VIEW_ATT_FILE_UP_CONT = 20;
	public static final int VIEW_ATT_FILE_DOWN = 21;
	public static final int VIEW_ATT_FILE_DOWN_CONT = 22;
	public static final String USER_STATUS_CHAT_OUT = "0";
	public static final String USER_STATUS_CHAT_IN = "1";
	public static final String USER_STATUS_CHAT_IDEL = "2";
	public static final String USER_STATUS_CHAT_CHATTING = "3";
	public static final String USER_STATUS_CHAT_TYPING = "4";
	public static final int USER_STATUS_OFFLINE = 0;
	public static final int USER_STATUS_ONLINE = 1;
	public static final int USER_STATUS_IDEL = 2;
	public static final int USER_STATUS_CHATTING = 3;
	public static final int USER_STATUS_TYPING = 0;
	public static final String USER_STATUS_STR_OFFLINE = "Offline";
	public static final String USER_STATUS_STR_ONLINE = "Online";
	public static final String USER_STATUS_STR_IDEL = "Idle";
	public static final String USER_STATUS_STR_CHATTING = "Online";
	public static final String USER_STATUS_STR_TYPING_TXT = "typing";
	public static final String USER_STATUS_STR_TYPING = "typing...";
	public static final String ATT_START_CMD = "1";
	public static final String ATT_CHUNK_CMD = "2";
	public static final String ATT_END_CMD = "3";
	public static final String FILE_START_CMD = "4";
	public static final String FILE_CHUNK_CMD = "5";
	public static final String FILE_END_CMD = "6";
	public static final String ATT_ORG_DOWNLOAD_TYPE = "0";
	public static final String ATT_THUMB_DOWNLOAD_TYPE = "1";
	public static final String PROFILE_SETTINGS = "Profile";
	public static final String CHAT_SETTINGS = "Chat Settings";
	public static final String SECURITY_SETTINGS = "Security Settings";
	public static final String RESET_SETTINGS = "Reset Password";
	public static final String BROADCAST_SETTINGS = "Broadcast Message";
	public static final String UPDATE_APP_SETTINGS = "Check for Update";
	public static final String WEB_SUPPORT_SETTINGS = "Web Support";
	public static final String DISTRIBUTE_APP_SETTINGS = "Distribute";
	public static final String TECHNICAL_APP_SUPPORT_SETTINGS = "Technical Support";
	public static final int Small_Font_Size = 16;
	public static final int Medium_Font_Size = 24;
	public static final int Large_Font_Size = 32;
	public static final int AUTO_DELETE_NORMAL_MESSAGES_COUNT = 3;
	public static final int AUTO_DELETE_BRIEFCASE_MESSAGES_COUNT = 7;
	public static final String ASK_PASSWORD_NEVER_COUNT = "-1";
	public static final String ASK_PASSWORD_FIRST_TIME_ONLY_COUNT = "100000000";
	public static final String ASK_PASSWORD_EVERY_TIME_COUNT = "0";
	public static final int ASK_PASSWORD_DEFAULT_COUNT = 100000000;
	public static final String ASK_VERIFY_USER = "1";
	public static final String ASK_NOT_VERIFY_USER = "0";

	public static final String MONTHS_TXT = "Months";
	public static final String HOURS_TXT = "Hour";
	public static final String MINUTES_TXT = "Minutes";
	public static final String DAYS_TXT = "Days";

	public static final String FILE_DELETE = "0";
	public static final String FILE_ADD = "1";
	public static final String FILE_MODULE_PROFILE_TYPE = "0";
	public static final String FILE_PROFILE_USER_TYPE = "0";
	public static final String FILE_PROFILE_GROUP_TYPE = "1";

	public static final String CALL_APP = "1";
	public static final String CALL_NORMAL = "2";
	public static final String APP_INIT = "3";
	public static final String CALL_NONE = "6";
	public static final String VIDEO_CALL_RELAY = "7";
	public static final String TCP_VIDEO_RTP_CALL_RELAY = "8";

	public static final int RTP_PKT_VOICE_CALL = 1;
	public static final int TCP_PKT_VOICE_CALL = 2;
	public static final int RTP_PKT_VIDEO_CALL = 3;
	public static final int TCP_PKT_VIDEO_CALL = 4;
	// public static final int TCP_PKT_VIDEO_CALL_LATEAST = 9;//ABDNT

	public static final int RTP_PKT_VOICE_CALL_V2 = 9;
	public static final int TCP_PKT_VOICE_CALL_V2 = 10;
	// public static final int RTP_PKT_VIDEO_CALL_V2 = 3;
	public static final int TCP_PKT_VIDEO_CALL_V2 = 11;

	public static final String CALL_INCOMING = "Incoming";
	public static final String CALL_OUTGOING = "Outgoing";
	public static final String CALL_MISSED = "Missed";
	public static final String CALL_CANCELED = "Canceled";
	public static final String CALL_BUSY = "Canceled";
	public static final String CALL_OFFLINE = "Canceled";

	public static final int CALL_INCOMING_NUM = 1;
	public static final int CALL_OUTGOING_NUM = 2;
	public static final int CALL_MISSED_NUM = 3;

	public static final int CHATING_PREVIEW_MESSAGE = 0;
	public static final int CHATING_PREVIEW_INFO = 2;
	public static final int CHATING_PREVIEW_CALL = 3;
	public static final int CHATING_PREVIEW_PROPIC = 4;
	public static final int CALL_RECEPIENT_BACKGROUND = 47113;
	public static final int CALL_TIME_BACKGROUND = 47114;

	public static final String OFFLINE = "OFFLINE";
	public static final String BUSY = "BUSY";
	public static final String CALLING = "CALLING";
	public static final String RINGING = "RINGING";
	public static final String ACCEPTING = "ACCEPTING";
	public static final String REJECTING = "REJECTING";
	public static final String ACCEPTED = "ACCEPTED";
	public static final String REJECTED = "REJECTED";
	public static final String NOANSWER = "NOANSWER";
	public static final String ENDED = "ENDED";
	public static final String NOSUPPORT = "NOSUPPORT";
	public static final String SERVERDOWN = "SERVERDOWN";
	public static final String ERRMSG = "ERRMSG";
	public static final String HOLDON = "HOLDON";// CALLHOLD
	public static final String HOLDOFF = "HOLDOFF";// CALLHOLD
	public static final String VIDEOON = "VIDEOON";// CALLHOLD
	public static final String VIDEOOFF = "VIDEOOFF";// CALLHOLD
	public static final String MUTEON = "MUTEON";// CALLHOLD
	public static final String MUTEOFF = "MUTEOFF";// CALLHOLD

	public static final String IDLE_STATE = "IDLE";
	public static final String TRYING_STATE = "TRYING";
	public static final String CALLING_STATE = "CALLING";
	public static final String RINGING_STATE = "RINGING";
	public static final String ANSWERING_STATE = "ANSWERING";
	public static final String ACCEPTING_STATE = "ACCEPTING_STATE";
	public static final String REJECTING_STATE = "REJECTING_STATE";
	public static final String ESTABLISHING_STATE = "ESTABLISHING";
	public static final String REJECTED_STATE = "REJECTED";
	public static final String TALKING_STATE = "TALKING";
	public static final String ENDED_STATE = "ENDED";
	public static final String HANGUP_STATE = "HANGUP";
	public static final String NOANSWER_STATE = "NOANSWER";
	public static final String NOSUPPORT_STATE = "NOSUPPORT";
	public static final String SERVERDOWN_STATE = "SERVERDOWN";
	public static final String ERRMSG_STATE = "ERRMSG";
	public static final String HOLDON_STATE = "HOLDON";// CALLHOLD
	public static final String HOLDOFF_STATE = "HOLDOFF";// CALLHOLD
	public static final String VIDEOON_STATE = "VIDEOON";// CALLHOLD
	public static final String VIDEOOFF_STATE = "VIDEOOFF";// CALLHOLD
	public static final String MUTEON_STATE = "MUTEON";// CALLHOLD
	public static final String MUTEOFF_STATE = "MUTEOFF";// CALLHOLD

	public static final String HOLDON_STATE_TEXT = "Call on Hold ...";
	public static final String HOLDOFF_STATE_TEXT = "HOLDOFF...";
	public static final String IDLE_STATE_TEXT = "Idle...";
	public static final String BUSY_STATE_TEXT = "Busy...";
	public static final String TRYING_STATE_TEXT = "Trying...";
	public static final String CALLING_STATE_TEXT = "Calling...";
	public static final String RINGING_STATE_TEXT = "Ringing...";
	public static final String ANSWERING_STATE_TEXT = "Answering...";
	public static final String ACCEPTING_STATE_TEXT = "Accepting...";
	public static final String ESTABLISHING_STATE_TEXT = "Establishing...";
	public static final String REJECTED_STATE_TEXT = "Rejected...";
	public static final String REJECTING_STATE_TEXT = "Rejecting...";
	public static final String TALKING_STATE_TEXT = "(Secured)";
	public static final String NOANSWER_STATE_TEXT = "No Answer...";
	public static final String HANGUP_STATE_TEXT = "Hanging up...";
	public static final String NOSUPPORT_STATE_TEXT = "No Support...";
	public static final String SERVERDOWN_STATE_TEXT = "Server Down...";
	public static final String ERRMSG_STATE_TEXT = "Server Error...";
	public static final String ACTION_SHOW_CHAT_VIEW = "1";
	public static final String ACTION_UPDATE_CALL_STATUS_TEXT = "2";
	public static final String ACTION_STOP_CLOCK = "3";
	public static final String ACTION_SHOW_CALLING_VIEW = "4";
	public static final String ACTION_START_CLOCK = "5";
	public static final String ACTION_SHOW_CALL_LOG_VIEW = "6";
	public static final String ACTION_SHOW_VIDEO_CALLING_VIEW = "7";
	public static final String ACTION_SHOW_VIDEO_CALLING_WITH_RTP_VOIC_CALL_VIEW = "8";
	public static final String VIEW_MODE_VOICE_ONLY_CALL_APP_TO_APP = "1";
	public static final String VIEW_MODE_VIDEO_CALL_BOTH = "2";
	public static final String VIEW_MODE_VIDEO_CALL_SEND_ONLY = "3";
	public static final String VIEW_MODE_VIDEO_CALL_RECEIVE_ONLY = "4";
	public static final String VIEW_MODE_VIDEO_CALL_FORCESTOP = "5";
	public static final String GET_PHONE_RINGTONE_MODE = "GET_PHONE_RINGTONE_MODE";
	public static final String PHONE_RINGTONE_MODE = "1";
	public static final String APPLICATION_RINGTONE_MODE = "2";
	public static final int SOUND_MSG_RECEIVED_BOTH = 1;
	public static final int SOUND_MSG_RECEIVED_GROUP_BG = 2;
	public static final int SOUND_MSG_RECEIVED_USER_BG = 3;
	public static final int SOUND_MSG_SEND = 4;
	public static final int SOUND_CALL_RINGING = 5;
	public static final int SOUND_CALL_ANSWERING = 6;
	public static final int SOUND_CALL_ESTABLISHING = 7;
	public static final int SOUND_CALL_BUSY = 8;
	public static final int SOUND_CALL_HOLD = 9;
	public static final int SOUND_CALL_CONNECTING = 10;
	public static final int PHONE_PERMISSION = 1;
	public static final String online = "Online";
	public static final String offline = "Offline";
	public static final String idle = "Idle";
	public static final String chating = "chating";
	public static final String typing = "typing...";
	public static final int NORMAL_SELECT_FRAGMENT = 1;
	public static final int FORWARD_SELECT_FRAGMENT = 2;
	public static final int NEW_CHAT_SELECT_FRAGMENT = 4;
	public static final int CHAT_SELECTED_DELETE = 1;
	public static final int CHAT_CLEAR_ALL = 2;
	public static final int CHAT_SELECTED_BRIEFCASE = 3;
	public static final int CHAT_SELECTED_FORWARD = 4;
	public static final int CHAT_RECENT_SELECTED_DELETE = 6;
	public static final int GROUP_SELECTED_EXIT = 7;
	public static final int GROUP_SELECTED_REMOVE_MEMBER = 8;
	public static final int GROUP_ADMIN_CHANGE_ALERT = 9;
	public static final int CALL_LOG_SELECTED_DELETE = 10;
	public static final int GROUP_SELECTED_DELETE = 11;
	public static final int CHAT_SELECTED_REPLY = 12;
	public static final int IMFROM_FOR_MESSAGE = 0;
	public static final int IMFROM_FOR_CALL = 2;
	public static final int IMFROM_FOR_GROUP = 3;
	public static final int IMFROM_FOR_SERVER = 3;
	public static final String MESSAGE_KEY_TEXT = "Message";
	public static final String REG_MODE_TEXT = "RegMode";
	public static final String IM_MESSAGE = ConstantsUtil.MESSAGE_KEY_TEXT;

	// Alert Type value
	public static final String TEXT_MIME_TYPE = "text/plain";
	public static final String PDF_MIME_TYPE = "application/pdf";
	public static final String DOC_MIME_TYPE = "application/msword";
	public static final String DOCX_MIME_TYPE = "application/vnd.openxmlformats-officedocument.wordprocessingml.document";
	public static final String XLS_MIME_TYPE = "application/vnd.ms-excel";
	public static final String XLXS_MIME_TYPE = "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet";
	public static final String PPT_MIME_TYPE = "application/vnd.ms-powerpoint";
	public static final String PPTX_MIME_TYPE = "application/vnd.openxmlformats-officedocument.presentationml.presentation";
	public static final String NOT_DOCUMENT_TEXT = "No-Document";
	public static final String DEFAULT_DOCUMENT_PAGECOUNT_TEXT = "0";
	public static final String DEFAULT_MEDIAID_TEXT = "0";
	public static final int MAX_ITEM_FORWARD_LIMIT = 10;
	public static final int MAX_USER_FORWARD_LIMIT = 10;
	public static final String MAX_ITEM_FORWARD_LIMIT_TXT = "Maximum items forward limit 10.";
	public static final String MAX_USER_FORWARD_LIMIT_TXT = "Maximum users forward limit 10.";
	public static final int MAX_ATT_SIZE_LIMIT = 20;
	public static final int MAX_ATT_UPLOAD_COUNT_LIMIT = 5;
	public static final String MAX_ATT_UPLOAD_COUNT_LIMIT_TXT = "Maximum upload at a time limit 5.";
	public static final int MAX_TEXT_SIZE_LIMIT = 8192;
	public static final String MAX_TEXT_SENT_LIMIT_TXT = "Maximum 8k only allowed to send. Are you sure you want to send only first 8k?";
	public static final int MAX_GROUP_MEMBER_LIMIT = 100;
	public static final String MAX_GROUP_MEMBER_LIMIT_TXT = "Maximum group member limit reached.";
	public static final String MAX_STATUS_LIMIT_TXT = "Maximum 160 characters only allowed to set as status.";
	public static final int MAX_CRASH_LOG_FILE_LIMIT = 524288;
	public static final String CRASH_LOG_FILE_NAME_TXT = "crash_log.txt";
	public static final String CRASH_LOG_MOB_NUMBER_TXT = "MobileNumber";
	public static final String CRASH_LOG_OS_VERSION_TXT = "OSVersion";
	public static final String CRASH_LOG_DEVICE_MODEL_TXT = "PhoneModel";
	public static final String CRASH_LOG_APP_VERSION_TXT = "AppVersion";
	public static final String CRASH_LOG_SUMMARY_TXT = "Summary";
	public static final String CRASH_LOG_DATE_TIME_TXT = "ClientDateTime";
	public static final String CRASH_LOG_PLATFORM_TXT = "Platform";
	public static final String IMAGE_TEXT_STRING = "Image";
	public static final String VIDEO_TEXT_STRING = "Video";
	public static final String AUDIO_TEXT_STRING = "Audio";
	public static final String LOCATION_TEXT_STRING = "Location";
	public static final String BCARD_TEXT_STRING = "Business Card";
	public static final String FILE_TEXT_STRING = "Document";
	public static final String CERTIFICATE_PEM_EXT_TXT = ".pem";
	public static final String CERTIFICATE_DER_EXT_TXT = ".der";
	public static final String CERTIFICATE_CRT_EXT_TXT = ".crt";
	public static final String CERTIFICATE_SERVER_NAME = "regsvr.crt";
	public static final String CERTIFICATE_SERVER_NAME_RECEIVED = "msgsvr_DH.crt";
	public static final String CERTIFICATE_IA_NAME = "ia.crt";
	public static final String DEFAULT_SIGNATURE_ALGORITHM = "SHA512withECDSA";
	public static final int STATUS_MAXIMUM_LIMIT = 160;
	public static final int VIDEO_CALL_CHUNK_SIZE = 768;
	public static final String Link_Server = "Mraijeb Server";
	public static final String Administrator = "administrator";
	public static int LOW = 0;
	public static int MID = 500;
	public static int HIGH = 1000;
	public static String TEMP_FILE_VIEWER_TEXT = " ";
	public static String MESSAGING_SERVER_LKEY_ID = "LKey";

	public static String CODEC_OPUS = "1";
	public static String CODEC_AAC_ELD = "2";

	public static String LOCAL_HOST_IP = "127.0.0.1";

	public static String PROTOCOL_COMMAND_TCP = "1";
	public static String PROTOCOL_COMMAND_TCP_WITH_TUNNEL = "2";
	public static String PROTOCOL_VOICE_TCP = "3";
	public static String PROTOCOL_VOICE_TCP_WITH_TUNNEL = "4";
	public static String PROTOCOL_VOICE_RTP = "5";
	public static String PROTOCOL_VIDEO_TCP = "6";
	public static String PROTOCOL_VIDEO_TCP_WITH_TUNNEL = "7";
	public static String PROTOCOL_VIDEO_RTP = "8";

	public static int OS_VERSION_IOS = 1;
	public static int OS_VERSION_ANDROID = 2;
	public static int OS_VERSION_ANDROID_BLACKPHONE = 3;
	public static int OS_VERSION_DESKTOP = 4;
	public static String Forward_document_Outside_Uri = null;// ABDNTDOC

	public static final String RECENT_CAHT_STR = "Chat";
	public static final String CONTACTS_STR = "Contacts";
	public static final String GROUP_STR = "Group";
	public static final String KEYPAD_STR = "Keypad";
	public static final String CALL_LOG_STR = "Call Log";
	public static final String BRIEFCASE_STR = "Briefcase";
	public static final String SETTINGS_STR = "Settings";
	public static final String MORE_STR = "More";
	public static final String UPDATE_STR = "Update";

	public static final String ACCOUNT_TYPE = "com.general.android.messagingapp.six";
	public static final String ACCOUNT_NAME = "Mraijeb ";
	public static final String ACCOUNT_TOKEN = "12345";
	public static boolean APP_awake = false;
	public static boolean phone_locked = false;// ABDNT
	public static boolean CALL_NOTI_RECHED = false;
	public static boolean IS_FROM_NOTIFICATION = false;

	public static int SERVER_LOCAL = 1;
	public static int SERVER_PRODUCTION_STAGING = 2;
	public static int SERVER_PRODUCTION_FINAL = 3;

	public static String PROTOCOL_CAll_AUTO_CONNECT = "1";
	public static String PROTOCOL_CAll_CLICK_CONNECT = "0";

	public static String SSH_CONNECT_INITIAL_PACKET_TYPE = "1";
	public static String SSH_CONNECT_NORMAL_PACKET_TYPE = "2";

	public static final int JOB_NETWORK_STATE_CHANGE = 100;

	public static String KEY_MSG = "0";
	public static String KEY_CALL = "1";
	public static String KEY_BOTH = "2";

	public static String KEY_GENERATION_NORMAL = "0";
	public static String KEY_GENERATION_SPECIFIC = "2";

	public static final String KEYSTORE_ALIAS_BIO = "mjb_bio_key";
	public static final String KEYSTORE_ALIAS_CALL_RELATED_MAP = "MYALIASCALLMAP";
	public static final String KEYSTORE_ALIAS_CALL_PRIVATE_DH = "MYALIASPVTDH";
	public static final String KEYSTORE_ALIAS_CALL_PUBLIC_DH = "MYALIASPUBDH";
	public static final String KEYSTORE_ALIAS_CALL_PRIVATE_DSA = "MYALIASPVTDSA";
	public static final String KEYSTORE_ALIAS_CALL_PUBLIC_DSA = "MYALIASPUBDSA";
	public static final String KEYSTORE_ALIAS_PUBLIC_IPADDRESS = "MYALIASPUBIP";// CALLFROMNOT
	public static final String KEYSTORE_ALIAS_PUBLIC_PORT = "MYALIASPUBPORT";// CALLFROMNOT
	public static final String KEYSTORE_ALIAS_MOBILE_NUMBER = "MYALIASMOBILE";// CALLFROMNOT

	public static final int MUTE_BUTTON_CLICKED = 1;
	public static final int VIDEO_BUTTON_CLICKED = 2;

	public static final String RESEND_AVAILABLE_ONLY = "0";
	public static final String RESEND_NEW_IMREGKEY = "1";

	public static final String WRONG_PASSWORD_TXT = "syso";

	public static final int PAUSE = 100;
	public static final int RESUME = 200;
	public static final int BUTTON_CLICKED = 300;

}
